import { darkTheme, Theme } from '@rainbow-me/rainbowkit';
import { merge } from 'lodash';
import { THEME_COLORS } from './constants';

export const rainbowkitTheme: Theme = merge(darkTheme(), {
  colors: {
    modalBackground: THEME_COLORS.backgroundSubtle,
    modalText: THEME_COLORS.text,
    modalTextSecondary: THEME_COLORS.textDim,
    profileForeground: THEME_COLORS.background,
    accentColor: THEME_COLORS.primary,
    accentColorForeground: THEME_COLORS.text,
    actionButtonBorder: THEME_COLORS.border,
    actionButtonBorderMobile: THEME_COLORS.border,
    actionButtonSecondaryBackground: THEME_COLORS.backgroundMenu,
    closeButton: THEME_COLORS.textGray,
    closeButtonBackground: THEME_COLORS.backgroundSubtle,
    connectButtonBackground: THEME_COLORS.backgroundSubtle,
    connectButtonBackgroundError: THEME_COLORS.errorBright,
    connectButtonInnerBackground: THEME_COLORS.backgroundMenu,
    connectButtonText: THEME_COLORS.text,
    connectButtonTextError: THEME_COLORS.text,
    connectionIndicator: THEME_COLORS.connected,
    downloadBottomCardBackground: THEME_COLORS.background,
    downloadTopCardBackground: THEME_COLORS.backgroundSubtle,
    error: THEME_COLORS.errorBright,
    generalBorder: THEME_COLORS.border,
    generalBorderDim: THEME_COLORS.borderDim,
    menuItemBackground: THEME_COLORS.backgroundMenu,
    modalBackdrop: THEME_COLORS.backdrop,
    modalBorder: THEME_COLORS.border,
    modalTextDim: THEME_COLORS.textDim,
    profileAction: THEME_COLORS.backgroundSubtle,
    profileActionHover: THEME_COLORS.backgroundMenu,
    selectedOptionBorder: THEME_COLORS.primary,
    standby: THEME_COLORS.standby,
  },
  radii: {
    actionButton: '12px',
    connectButton: '12px',
    menuButton: '12px',
    modal: '20px',
    modalMobile: '20px',
  },
  shadows: {
    connectButton: '0 4px 12px rgba(0, 0, 0, 0.4)',
    dialog: '0 8px 32px rgba(0, 0, 0, 0.5)',
    profileDetailsAction: '0 2px 6px rgba(0, 0, 0, 0.3)',
    selectedOption: '0 2px 6px rgba(0, 0, 0, 0.3)',
    selectedWallet: '0 2px 6px rgba(0, 0, 0, 0.3)',
    walletLogo: '0 2px 16px rgba(0, 0, 0, 0.3)',
  },
});
