name: Update Vercel ENV for bgt-market

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/.env.bgt-market'
      - '.github/workflows/bgt-market.deployment.yml'
      - 'apps/bgt-market/**'

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Export secrets to env
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install dependencies
        run: npm install axios dotenv fs  --legacy-peer-deps --no-save --no-package-lock

      - name: Process env file with Node.js
        env:
          ENV_FILE: .github/workflows/.env.bgt-market
          PROJECT_NAME: bgt-market
·         PROJECT_ID: prj_Yhv6hufFe068byTjwTCRds5PP4YB
        run: node .github/scripts/update-env.js
