- name: Install jq and gh CLI
  run: |
    sudo apt-get update
    sudo apt-get install -y jq gh

- name: Authenticate gh CLI with PAT
  env:
    WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
  run: |
    echo "$WORKFLOW_GITHUB_TOKEN" | gh auth login --with-token --hostname github.com

- name: Load and replace .env.workflow variables
  run: |
    secrets_json=$(gh api repos/$GITHUB_REPOSITORY/actions/secrets)
    while IFS= read -r line; do
      while [[ "$line" =~ (\$\{([^}]+)\}) ]]; do
        var_name="${BASH_REMATCH[2]}"
        var_value=$(echo "$secrets_json" | jq -r --arg var_name "$var_name" '.secrets | map(select(.name == $var_name)) | .[0].value // empty')
        line="${line//${BASH_REMATCH[1]}/$var_value}"
      done
      echo "$line"
    done < .github/workflows/.env.workflow > .github/workflows/.env.workflow.tmp
    mv .github/workflows/.env.workflow.tmp .github/workflows/.env.workflow

- name: Update Vercel Environment Variables
  run: |
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
      if [[ ! -z "$key" && "$key" != \#* ]]; then
        json_payload=$(jq -n --arg key "$key" --arg value "$value" --argjson target '["production", "preview"]' '{key: $key, value: $value, type: "plain", target: $target}')
        curl -X DELETE "https://api.vercel.com/v10/projects/$PROJECT_ID/env/$key?teamId=$TEAM_ID" \
          -H "Authorization: Bearer $VERCEL_TOKEN" \
          -H "Content-Type: application/json"
        curl -X POST "https://api.vercel.com/v10/projects/$PROJECT_ID/env?teamId=$TEAM_ID" \
          -H "Authorization: Bearer $VERCEL_TOKEN" \
          -H "Content-Type: application/json" \
          --data "$json_payload"
      fi
    done < .github/workflows/.env.workflow
