name: Update Vercel ENV for reward-vault-market

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件
    paths:
      - .env
      - '.github/workflows/reward-deployment.yml'
      - 'apps/reward-vault-market/**'

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Secrets Directly in .env.workflow
        run: |
          # 遍历所有环境变量并替换
          while IFS= read -r line; do
            if [[ $line =~ \${{ secrets\.([a-zA-Z0-9_]+) }} ]]; then
              secret_name="${BASH_REMATCH[1]}"
              secret_value="${!secret_name}"

              if [[ -n "$secret_value" ]]; then
                echo "Replacing $secret_name in .env.workflow"
                sed -i "s|\${{ secrets.$secret_name }}|$secret_value|g" .github/workflows/.env.workflow
              else
                echo "Warning: Secret $secret_name is not defined!"
              fi
            fi
          done < .github/workflows/.env.workflow
    
      - name: Print Updated .env.workflow
        run: |
          echo "Updated .env.workflow:"

      - name: Update Vercel Environment Variables for Project
        env:
          source .env  # 载入环境变量
          VERCEL_TOKEN: ${{ secrets.WORKFLOW_VERCEL_TOKEN }}
          TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          PROJECT_NAME: reward-vault-market
          PROJECT_ID: prj_Yhv6hufFe068byTjwTCRds5PP4YB

        run: |
          while IFS='=' read -r key value || [[ -n "$key" ]]; do
            if [[ ! -z "$key" && "$key" != \#* ]]; then
              echo "Setting $key in Vercel..."
              curl -X POST "https://api.vercel.com/v10/projects/$PROJECT_ID/env?teamId=$TEAM_ID" \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{
                \"key\": \"$key\",
                \"value\": \"$value\",
                \"type\": \"plain\",
                \"target\": [\"production\", \"preview\"]
              }"
            fi
          done < .env
