name: Update Vercel ENV for reward-vault-market

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件
    paths:
      - .env
      - '.github/workflows/reward-deployment.yml'
      - 'apps/reward-vault-market/**'

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Secrets in .env.workflow
        run: |
          cp .github/workflows/.env.workflow .env  # 复制文件，避免修改原文件

          # 遍历 .env 文件中的所有 `secrets.*`
          grep -o '\${{ secrets\.[^}]* }}' .env | while read -r match; do
            secret_name=$(echo $match | sed -E 's/\${{ secrets\.([^}]*) }}/\1/')
            secret_value="${!secret_name}"

            if [[ -n "$secret_value" ]]; then
              echo "Replacing $match with actual secret value"
              sed -i "s|$match|$secret_value|g" .env
            else
              echo "Warning: Secret $secret_name is not defined!"
            fi
          done

      - name: Print Updated ENV File
        run: |
          echo "Updated ENV File:"
          cat .env

      - name: Update Vercel Environment Variables for Project
        env:
          source .env  # 载入环境变量
          VERCEL_TOKEN: ${{ secrets.WORKFLOW_VERCEL_TOKEN }}
          TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          PROJECT_NAME: reward-vault-market
          PROJECT_ID: prj_Yhv6hufFe068byTjwTCRds5PP4YB

        run: |
          while IFS='=' read -r key value || [[ -n "$key" ]]; do
            if [[ ! -z "$key" && "$key" != \#* ]]; then
              echo "Setting $key in Vercel..."
              curl -X POST "https://api.vercel.com/v10/projects/$PROJECT_ID/env?teamId=$TEAM_ID" \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{
                \"key\": \"$key\",
                \"value\": \"$value\",
                \"type\": \"plain\",
                \"target\": [\"production\", \"preview\"]
              }"
            fi
          done < .env
