name: Update Multiple ENV for Multiple Vercel Projects

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug VERCEL_TOKEN
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "ERROR: VERCEL_TOKEN is EMPTY!"
            exit 1
          else
            echo "VERCEL_TOKEN is set with length: ${#VERCEL_TOKEN}"
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.WORKFLOW_VERCEL_TOKEN }}

      - name: Update Vercel Environment Variables for Multiple Projects
        env:
          VERCEL_TOKEN: ${{ secrets.WORKFLOW_VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          PROJECTS: '["prj_Yhv6hufFe068byTjwTCRds5PP4YB"]' 
          PROJECTS_JSON: '{
            "reward_vault_market": "prj_Yhv6hufFe068byTjwTCRds5PP4YB",
          }' # 这里填入你的多个项目 ID
          ENV_VARS: '{
            "TEST_ACTION_ENV_1": "value1-1",
            "TEST_ACTION_ENV_2": "value2-2",
            "TEST_ACTION_ENV_3": "value3-3"
          }'  # 这里填入你要更新的多个环境变量
        run: |
          for PROJECT_ID in $(echo $PROJECTS | jq -r '.[]'); do
            echo "Updating ENV for project: $PROJECT_ID"
            
            for KEY in $(echo $ENV_VARS | jq -r 'keys[]'); do
              VALUE=$(echo $ENV_VARS | jq -r --arg KEY "$KEY" '.[$KEY]')
              
              echo "Updating $KEY=$VALUE"
              
              curl -X POST "https://api.vercel.com/v10/projects/$PROJECT_ID/env?teamId=$VERCEL_TEAM_ID" \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{
                "key": "'"$KEY"'",
                "value": "'"$VALUE"'",
                "target": ["production", "preview"]
              }'

              echo "$KEY updated for project: $PROJECT_ID"
            done
          done